name: apple_store
description: "A app to view and download product details as PDF"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  google_fonts: ^6.2.1
  pdf: ^3.11.3
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  share_plus: ^11.0.0
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/core/assets/google-icon.png